# Generated by Django 4.1.6 on 2023-04-24 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("librerias", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="libro",
            name="imagen",
            field=models.ImageField(upload_to="img/"),
        ),
    ]
