# Generated by Django 4.1.6 on 2023-04-25 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("librerias", "0002_alter_libro_imagen"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="libro",
            name="imagen",
        ),
        migrations.AddField(
            model_name="libro",
            name="imagen_url",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
