# Generated by Django 4.1.6 on 2023-04-26 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("librerias", "0005_producto_delete_reserva"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Producto",
        ),
    ]
